const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const Cafe = require('../models/Cafe');
const Category = require('../models/Category');
const MenuItem = require('../models/MenuItem');
require('dotenv').config();

const seedCafes = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/cafe_chaska');
        console.log('MongoDB Connected for Seeding');

        // Clear existing data
        await Cafe.deleteMany({});
        await Category.deleteMany({});
        await MenuItem.deleteMany({});
        console.log('Cleared existing data');

        const categoriesList = ['Beverages', 'Snacks', 'Mains', 'Desserts', 'Specials'];

        for (let i = 1; i <= 50; i++) {
            const idStr = i.toString().padStart(3, '0');
            const cafeSlug = `CAFE${idStr}`;
            const password = cafeSlug;

            const salt = await bcrypt.genSalt(10);
            const hashedPassword = await bcrypt.hash(password, salt);

            const newCafe = new Cafe({
                name: `Cafe Chaska ${idStr}`,
                slug: cafeSlug,
                password: hashedPassword,
                theme: 'japandi'
            });

            await newCafe.save();

            // Create Categories
            for (const catName of categoriesList) {
                const newCat = new Category({
                    name: catName,
                    cafeId: cafeSlug
                });
                const savedCat = await newCat.save(); // Save to get _id or id

                // Create 10 Items per Category
                const items = [];
                for (let j = 1; j <= 10; j++) {
                    items.push({
                        name: `${catName} Item ${j}`,
                        description: `Delicious ${catName.toLowerCase()} with premium ingredients.`,
                        price: Math.floor(Math.random() * 500) + 50,
                        imageUrl: 'https://placehold.co/400',
                        categoryId: savedCat.id, // Use the UUID generated by schema
                        cafeId: cafeSlug,
                        ingredients: ['Salt', 'Pepper', 'Love']
                    });
                }
                await MenuItem.insertMany(items);
            }
        }

        console.log(`Successfully seeded 50 cafes with Menus.`);
        console.log('Login with CAFE001 / CAFE001');
        process.exit();

    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedCafes();
